package com.manji.elastic.api.controller.user.model;

import java.util.Date;

import com.wordnik.swagger.annotations.ApiModelProperty;

public class EditUserBody {
	/**
	 * 昵称
	 */
	private String nickname;
	/**
	 * 真实姓名
	 */
	private String realName;
	/**
	 * 头像
	 */
	private String headImg;
	/**
	 * 性别（男，女）
	 */
	private String gender;
	/**
	 * 出生年月日
	 */
	private Date birthDay;
	/**
	 * 星座
	 */
	private String constellation;
	/**
	 * 个人说明
	 */
	private String introduction;

	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elastic_user.nickname
	 * @return  the value of elastic_user.nickname
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "昵称")
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elastic_user.nickname
	 * @param nickname  the value for elastic_user.nickname
	 * @mbggenerated
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elastic_user.real_name
	 * @return  the value of elastic_user.real_name
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "真实姓名")
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elastic_user.real_name
	 * @param realName  the value for elastic_user.real_name
	 * @mbggenerated
	 */
	public void setRealName(String realName) {
		this.realName = realName == null ? null : realName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elastic_user.head_img
	 * @return  the value of elastic_user.head_img
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "头像")
	public String getHeadImg() {
		return headImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elastic_user.head_img
	 * @param headImg  the value for elastic_user.head_img
	 * @mbggenerated
	 */
	public void setHeadImg(String headImg) {
		this.headImg = headImg == null ? null : headImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elastic_user.gender
	 * @return  the value of elastic_user.gender
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "性别（男，女）")
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elastic_user.gender
	 * @param gender  the value for elastic_user.gender
	 * @mbggenerated
	 */
	public void setGender(String gender) {
		this.gender = gender == null ? null : gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elastic_user.birth_day
	 * @return  the value of elastic_user.birth_day
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "出生年月日")
	public Date getBirthDay() {
		return birthDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elastic_user.birth_day
	 * @param birthDay  the value for elastic_user.birth_day
	 * @mbggenerated
	 */
	public void setBirthDay(Date birthDay) {
		this.birthDay = birthDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elastic_user.constellation
	 * @return  the value of elastic_user.constellation
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "星座")
	public String getConstellation() {
		return constellation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elastic_user.constellation
	 * @param constellation  the value for elastic_user.constellation
	 * @mbggenerated
	 */
	public void setConstellation(String constellation) {
		this.constellation = constellation == null ? null : constellation.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column elastic_user.introduction
	 * @return  the value of elastic_user.introduction
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "个人说明")
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column elastic_user.introduction
	 * @param introduction  the value for elastic_user.introduction
	 * @mbggenerated
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}
}
