package com.manji.elastic.api.model;

import java.util.Date;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import com.wordnik.swagger.annotations.ApiModelProperty;

/**
 * 修改用户设置信息
 * @author ShyMe
 */
public class EditUserForm {
    /**
     * 昵称
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * 头像
     *
     * @mbggenerated
     */
    private String headImg;

    /**
     * 性别（男，女）
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * 出生年月日
     *
     * @mbggenerated
     */
    private String birthDay;

    /**
     * 喜欢的宠物
     *
     * @mbggenerated
     */
    private String likePet;

    /**
     * 养宠年限
     *
     * @mbggenerated
     */
    private String keepYears;

    /**
     * 兴趣爱好
     *
     * @mbggenerated
     */
    private String hobby;

    /**
     * 手机
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * 常出没-省
     *
     * @mbggenerated
     */
    private String oftenProvince;

    /**
     * 常出没-市
     *
     * @mbggenerated
     */
    private String oftenCity;

    /**
     * 常出没-区
     *
     * @mbggenerated
     */
    private String oftenCounty;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.nickname
     *
     * @return the value of ado_user.nickname
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "昵称")
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.nickname
     *
     * @param nickname the value for ado_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.head_img
     *
     * @return the value of ado_user.head_img
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "头像")
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.head_img
     *
     * @param headImg the value for ado_user.head_img
     *
     * @mbggenerated
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.gender
     *
     * @return the value of ado_user.gender
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "性别（男，女）")
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.gender
     *
     * @param gender the value for ado_user.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.birth_day
     *
     * @return the value of ado_user.birth_day
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "出生年月日")
    public String getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.birth_day
     *
     * @param birthDay the value for ado_user.birth_day
     *
     * @mbggenerated
     */
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.like_pet
     *
     * @return the value of ado_user.like_pet
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "喜欢的宠物")
    public String getLikePet() {
        return likePet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.like_pet
     *
     * @param likePet the value for ado_user.like_pet
     *
     * @mbggenerated
     */
    public void setLikePet(String likePet) {
        this.likePet = likePet == null ? null : likePet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.keep_years
     *
     * @return the value of ado_user.keep_years
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "养宠年限")
    public String getKeepYears() {
        return keepYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.keep_years
     *
     * @param keepYears the value for ado_user.keep_years
     *
     * @mbggenerated
     */
    public void setKeepYears(String keepYears) {
        this.keepYears = keepYears == null ? null : keepYears.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.hobby
     *
     * @return the value of ado_user.hobby
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "兴趣爱好")
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.hobby
     *
     * @param hobby the value for ado_user.hobby
     *
     * @mbggenerated
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.mobile
     *
     * @return the value of ado_user.mobile
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "手机")
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.mobile
     *
     * @param mobile the value for ado_user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.often_province
     *
     * @return the value of ado_user.often_province
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "常出没-省")
    public String getOftenProvince() {
        return oftenProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.often_province
     *
     * @param oftenProvince the value for ado_user.often_province
     *
     * @mbggenerated
     */
    public void setOftenProvince(String oftenProvince) {
        this.oftenProvince = oftenProvince == null ? null : oftenProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.often_city
     *
     * @return the value of ado_user.often_city
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "常出没-市")
    public String getOftenCity() {
        return oftenCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.often_city
     *
     * @param oftenCity the value for ado_user.often_city
     *
     * @mbggenerated
     */
    public void setOftenCity(String oftenCity) {
        this.oftenCity = oftenCity == null ? null : oftenCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ado_user.often_county
     *
     * @return the value of ado_user.often_county
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "常出没-区")
    public String getOftenCounty() {
        return oftenCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ado_user.often_county
     *
     * @param oftenCounty the value for ado_user.often_county
     *
     * @mbggenerated
     */
    public void setOftenCounty(String oftenCounty) {
        this.oftenCounty = oftenCounty == null ? null : oftenCounty.trim();
    }

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this,
				ToStringStyle.SHORT_PREFIX_STYLE);
	}
}
